# Ruff configuration file for SG_proj_005_sad
line-length = 120
target-version = "py312"

[lint]
select = ["E", "F", "I", "N", "UP", "B", "A", "C4", "SIM", "ARG", "PTH"]
ignore = [
    "E501", # Line too long
    "A003", # Class attribute is shadowing a python builtin
    "UP007", # Keep standard Union compatibility
    "E402", # Allow late imports for Windows OS patches and dynamic mock setups
    "E701", # Allow multiple statements on one line (colon) for concise logic
    "PTH",  # Allow standard os.path usage to keep compatibility with existing apps
]

[lint.isort]
combine-as-imports = true
